/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    brands: Brand;
    categories: Category;
    products: Product;
    reviews: Review;
    orders: Order;
    banners: Banner;
    pages: Page;
    'support-tickets': SupportTicket;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'support-tickets': SupportTicketsSelect<false> | SupportTicketsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName?: string | null;
  phone?: string | null;
  addresses?:
    | {
        label?: string | null;
        fullName: string;
        phone: string;
        line1: string;
        line2?: string | null;
        city: string;
        province?: string | null;
        postalCode?: string | null;
        country?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  wishlist?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  status?: ('active' | 'sold-out' | 'coming-soon' | 'draft') | null;
  featured?: boolean | null;
  platform?: ('playstation' | 'xbox' | 'switch' | 'pc' | 'universal') | null;
  category?: (number | Category)[] | null;
  brand?: (number | null) | Brand;
  sku?: string | null;
  /**
   * Selling price in PKR
   */
  price: number;
  /**
   * Original price — shown struck-through when higher than price (sale badge)
   */
  compareAtPrice?: number | null;
  stock?: number | null;
  /**
   * Average rating (seeded/derived from reviews)
   */
  rating?: number | null;
  reviewCount?: number | null;
  /**
   * Shown on product cards and listing pages
   */
  shortDescription?: string | null;
  /**
   * Optional notice shown prominently on the product page — e.g. "All prices subject to change", "Digital code — non-refundable", "Ships from UAE"
   */
  note?: string | null;
  /**
   * YouTube video URL or video ID — e.g. https://youtu.be/abc123 or https://www.youtube.com/watch?v=abc123
   */
  youtubeUrl?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional purchasable options (e.g. colour or edition). Leave empty for single-SKU products.
   */
  variants?:
    | {
        label: string;
        sku?: string | null;
        /**
         * Selling price for this variant (leave blank to use base product price)
         */
        price?: number | null;
        /**
         * Original/struck-through price for this variant (shows sale badge)
         */
        compareAtPrice?: number | null;
        stock: number;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  platform?: ('playstation' | 'xbox' | 'switch' | 'pc' | 'universal') | null;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  description?: string | null;
  showInNav?: boolean | null;
  navOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  customer: number | Customer;
  rating: number;
  title: string;
  comment: string;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status?: ('pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled') | null;
  paymentMethod?: 'cod' | null;
  customer?: (number | null) | Customer;
  items: {
    product?: (number | null) | Product;
    titleSnapshot: string;
    variantLabel?: string | null;
    imageUrl?: string | null;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
    id?: string | null;
  }[];
  subtotal: number;
  shippingCost: number;
  total: number;
  shippingAddress: {
    fullName: string;
    phone: string;
    email?: string | null;
    line1: string;
    line2?: string | null;
    city: string;
    province?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  eyebrow?: string | null;
  title: string;
  subtitle?: string | null;
  /**
   * Background image. Also used as the video poster when a video URL is set.
   */
  image: number | Media;
  /**
   * Optional: paste a direct MP4 URL to play a looping background video instead of the static image. The image above is used as the loading poster.
   */
  videoUrl?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  theme?: ('violet' | 'magenta' | 'cyan') | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer support queries submitted via the chat widget.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets".
 */
export interface SupportTicket {
  id: number;
  customerName: string;
  customerEmail: string;
  subject: string;
  message: string;
  status?: ('open' | 'replied' | 'closed') | null;
  /**
   * Write your reply here — saving will automatically email the customer.
   */
  reply?: string | null;
  repliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'support-tickets';
        value: number | SupportTicket;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  addresses?:
    | T
    | {
        label?: T;
        fullName?: T;
        phone?: T;
        line1?: T;
        line2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  wishlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  platform?: T;
  parent?: T;
  image?: T;
  description?: T;
  showInNav?: T;
  navOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  featured?: T;
  platform?: T;
  category?: T;
  brand?: T;
  sku?: T;
  price?: T;
  compareAtPrice?: T;
  stock?: T;
  rating?: T;
  reviewCount?: T;
  shortDescription?: T;
  note?: T;
  youtubeUrl?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        price?: T;
        compareAtPrice?: T;
        stock?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  customer?: T;
  rating?: T;
  title?: T;
  comment?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentMethod?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        titleSnapshot?: T;
        variantLabel?: T;
        imageUrl?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  total?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        email?: T;
        line1?: T;
        line2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  image?: T;
  videoUrl?: T;
  ctaLabel?: T;
  ctaHref?: T;
  theme?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets_select".
 */
export interface SupportTicketsSelect<T extends boolean = true> {
  customerName?: T;
  customerEmail?: T;
  subject?: T;
  message?: T;
  status?: T;
  reply?: T;
  repliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  storeName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  currency?: string | null;
  announcementText?: string | null;
  /**
   * Messages shown in the scrolling banner below the header.
   */
  tickerItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  mapLink?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'youtube' | 'tiktok' | 'discord';
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        columns?:
          | {
              heading: string;
              links?:
                | {
                    label: string;
                    href: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Slides shown in the homepage hero carousel. Use an image, or paste an MP4 URL for a looping video background.
   */
  heroSlides?:
    | {
        /**
         * Small badge text above the title, e.g. "New Arrival"
         */
        eyebrow?: string | null;
        title: string;
        subtitle?: string | null;
        /**
         * Background image. Also used as the video poster when a video URL is set.
         */
        image: number | Media;
        /**
         * Optional: paste a direct MP4 URL to play a looping background video. The image above is used as the loading poster.
         */
        videoUrl?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        theme?: ('violet' | 'magenta' | 'cyan') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Trust-badge cards shown below the hero slider.
   */
  valueProps?:
    | {
        icon: 'truck' | 'shield-check' | 'badge-check' | 'headset' | 'zap';
        title: string;
        description: string;
        accent: 'violet' | 'cyan' | 'emerald' | 'magenta';
        id?: string | null;
      }[]
    | null;
  latestArrivals?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    href?: string | null;
    /**
     * Select up to 10 products to feature as latest arrivals.
     */
    products?: (number | Product)[] | null;
  };
  platformSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Platform browse cards. The Platform field controls the accent colour and icon.
     */
    cards?:
      | {
          label: string;
          eyebrow?: string | null;
          description?: string | null;
          href: string;
          platform: 'playstation' | 'xbox' | 'switch' | 'pc' | 'universal';
          /**
           * Optional badge text, e.g. "Most Popular"
           */
          tag?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Product rails after the platform grid (e.g. PlayStation, Xbox, Switch). Rail 1 appears above the Brand Strip; rail 2 above the Promo Band; the rest follow after.
   */
  platformRails?:
    | {
        eyebrow: string;
        title: string;
        description?: string | null;
        href?: string | null;
        /**
         * Select up to 10 products for this rail.
         */
        products?: (number | Product)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small label shown above the scrolling brand logos.
   */
  brandStripHeading?: string | null;
  promoBand?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Feature tag pills shown below the subtitle.
     */
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * Category-based product rails shown at the bottom of the page. Admin hand-picks up to 10 products per rail.
   */
  categoryRails?:
    | {
        eyebrow: string;
        title: string;
        description?: string | null;
        href?: string | null;
        /**
         * Select up to 10 products for this rail.
         */
        products?: (number | Product)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  storeName?: T;
  tagline?: T;
  logo?: T;
  currency?: T;
  announcementText?: T;
  tickerItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  mapLink?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        image?: T;
        videoUrl?: T;
        ctaLabel?: T;
        ctaHref?: T;
        theme?: T;
        id?: T;
      };
  valueProps?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        accent?: T;
        id?: T;
      };
  latestArrivals?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        href?: T;
        products?: T;
      };
  platformSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        cards?:
          | T
          | {
              label?: T;
              eyebrow?: T;
              description?: T;
              href?: T;
              platform?: T;
              tag?: T;
              id?: T;
            };
      };
  platformRails?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        href?: T;
        products?: T;
        id?: T;
      };
  brandStripHeading?: T;
  promoBand?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  categoryRails?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        href?: T;
        products?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}